DROP TABLE IF EXISTS "_CEL_SF_CASE_ACTIVITIES"
;

CREATE TABLE "_CEL_SF_CASE_ACTIVITIES" (
	"_CASE_KEY" VARCHAR(50),
	 "ID" VARCHAR(50),
	"ACTIVITY_DE" VARCHAR(300),
	"ACTIVITY_EN" VARCHAR(300),
	"EVENTTIME" TIMESTAMP,
	"_SORTING" INT,
	"CHANGED_FIELD" VARCHAR(300),
	"CHANGED_FROM" VARCHAR(300),
	"CHANGED_TO" VARCHAR(300)
);
